CSRF_ENABLE: true
SECRET_KEY: "you-will-never-guess"

OPENID_PROVIDERS:
- name: "Google"
  url: "https://www.google.com/accounts/o8/id"

SQLALCHEMY_DATABASE_URI: "sqlite:///../temp/blog.db"
SQLALCHEMY_ECHO: on
